version: '2'
services:
    timiriscrm-app:
        image: timiriscrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://timiriscrm-postgresql:5432/timirisCrm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timiriscrm-postgresql:
        extends:
            file: postgresql.yml
            service: timiriscrm-postgresql
