version: '2'
services:
    timiriscrm-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/timirisCrm/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=timirisCrm
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
